spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/tickets_db
spring.datasource.username=postgres
spring.datasource.password=1
spring.jpa.hibernate.ddl-auto=update
jwt.secret=this-is-a-very-long-secret-key-for-jwt-signing-change-me-1234567890
jwt.expiration=86400000
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG